import { NextPage } from 'next'
import Head from 'next/head'

import LoginForm from '../components/LoginForm'

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className="min-h-screen bg-[url('../public/thunder.jpeg')] bg-cover bg-center flex justify-center">
        <LoginForm />
      </main>

      <footer></footer>
    </div>
  )
}

export default Login
